language: python

python:
  - "3.2"
  - "3.3"

install: 
   - pip install --use-mirrors -r requirements.txt
   - pip install --use-mirrors coveralls coverage

script:
   - coverage run --source=geofeed_validator setup.py test
   - coverage report -m

after_script:
   coveralls --verbose
